### ISSUE TITLE
MoCo Mask with Data doesnt fit - Registration missing?

### ISSUE THREAD

**Issue by MatthiasWeinhold** [thomaskuestner/TAToolbox#14]
Initial issues (Some solved):
1) Why are the segmentated areas / ROIs outside of patients body? (They fit now)

2) Masks don't seem to fit the image in any way (mirroring doesn't work either) (Now does)

3) Create new masks? -> Had been done. Apparently the provided masks (by a radiologist?) contained the right ROIs but they were somehow flipped somewhere in the process of data transportation... 

To- Do's:

The following points are vitally important for the methodology of the study thesis (Philipps*):

- [x] Verify if Masks were correctly oriented when struct was formed (via Features and their respective values)
   
    -[ ] First statistical analysis (standard deviation)

- [x] Wrrite script to export values of the struct 'MoCo' in order to analyse them in more advanced statistics in Matlab
-> This should contain the following methods:
- [x] ttest (for nullhypothsis) -> Confirm with the ttest implemented in Janas GUI?
- [ ]

.... To be extended/ upgraded

**Comment by thomaskuestner** [comment]
You need to consider the orientation of the masks as in:
```
[dImg, infoImg] = fReadDICOM(_PATH_TO_IMAGE_);
[lMask, infoMask] = fReadDICOM(_PATH_TO_MASK_);
if(infoMask.PerFrameFunctionalGroupsSequence(1).Item_1(1).PlanePositionSequence.Item_1.ImagePositionPatient(3) ~= infoImg(1).STag.SliceLocation)
   lMask = flipdim(lMask,3);
end
```
