### ISSUE TITLE
Texture Features verstehen und verifizieren

### ISSUE THREAD

**Issue by PhillyVanilly9119** [thomaskuestner/TAToolbox#17]
Grund: Unstimmige Werte bei ausgegebenen Features! Siehe Excel- Sheet in Git, bzw. Dummies (Jana)
**!!!! Achtung bisheriges Excel-Sheet hat falsche Wert-Feature-Zuordnung**

Analysieren der plausiblen Wertebereiche der verschiedenen TFs an Ordnung (Sortierung in Matrizen):

Globale Features (alle anderen auch?) diskretisieren nur in 64- Stufen. Hellster und Dunkelster Wert in ROI definieren die Grenzen, mit denen die Operatoren (TFs) arbeiten - Ein insgesamt sehr dunkles Bild kann eine sehr hohe Varianz haben, wenn nur z.B. 2 "Schwarztöne" im Bild sind (wichtig Werteinterpretation der Features!!!). 

Philipp:

- [x] TFs der GLRLM (sieh Excel- Sheet "...PhilsVersion.xls")

- [x] TFs GTSDM/ aka. GLCM

Matthias:

- [x] TFs der NGTDM

- [x] TFs der GLZSM

Zum Merken: Sqrt(var()) <= n/2 (n ist Anzahl der GW- Quantisierungsstufen)

**Comment by MatthiasWeinhold** [comment]
1. NGTDM - Berechnung in radiomics (Abweichung Jana Studienarbeit?)
Nur Voxel bei denen die Nachbarschaft aus ausschließlich NaNs besteht werden verworfen, alle anderen werden gewichtet in NGTDM-Matrix eingerechnet!

2. Bitte nur neues Excel-Sheet (Zuordnung-TFs-Radiomic-vs-Jana.xlsx) für Vergleich verwenden
